### PR TITLE
Upgrade stackbrew, fix gitCommit, remove 32bit images

### PR DESCRIPTION
**Pull request by HoustonPutman**

### CODE REVIEW

**Review by janhoy — APPROVED** [review]

**Comment by gus-asf** [comment]
Removing support for old stuff seems like something that should involve dev/user list discussion... ( didn't see it when I searched solr docker in my email, pardon me if I missed it)

**Comment by HoustonPutman** [comment]
That's fair, but this was kind of supported by accident. It's something that wasn't supported before, that we mistakenly added support for, and now have removed support for current and future versions. (9.0-9.4 still have those architectures, because they don't get updates).

But I agree this would be something to bring to the dev list in the future.

**Comment by janhoy** [comment]
The history here is that right after the 9.6 release I upgraded a cluster on my M1 Mac to the new version, but got some strange errors, Solr would not start, but threw some weird low-level JDK IO exception. I spend quite some time before realizing that due to some serious delays before Docker builders built the arm64 images, Docker on my M1 mac decided to insteal pull the armv7 32-bit images that fail due to 64/32 bit mismatch. Worse, even after the arm64 images became available, Docker would NOT pull those automatically until I deleted the faulty image or force-pulled the new.

I can imagine that the same would happen on some ARM based cloud server if it happened to auto upgrade immediately after a release announcement, but before the arm64 image was built (this can take 12+ hours).

I was not aware we even build a 32 bit image. And I cannot imagine what system would run Solr on such a chip. Some old RasPI perhaps, although nowdays even smaller systems are 64 bit, no?

Remember that Docker binary images is a convenience release and the supported architectures are clearly labeled on HUB, so we havent taken anything way or broken any promise, other than perhaps it is surprising to potential 32-bit users that support disappears in a minor release. Also, users can build whatever support they like using the Dockerfile we publish. Do you think we should do an ANNOUNCE type email about this?

**Comment by dsmiley** [comment]
I'd imagine such a user that expects/required 32 bit would find out relatively quickly; it's not a subtle thing.  It works or it doesn't.  So IMO no need to announce-to/warn users.

**Pull request merged**
