### PR TITLE
Remove stale versions

### PR DESCRIPTION
**Pull request by janhoy**
We should not pretend that we support v 9.0, 9.1, 9.2, 9.3 and 9.4 since they won't receive pathces.
Better remove them from the list at https://hub.docker.com/_/solr so people can see how old they are.

Q: Should this be part of the rel wizard, same way as we remove old releases from CDN?

### CODE REVIEW

**Comment by epugh** [comment]
Some automation or an explicit step would be good or this will get skipped in the future!

**Comment by HoustonPutman** [comment]
9.5 was just released, so I'd say it would be good to give a little bit of time before removing security updates for 9.4 at least. Otherwise I'm good with this.

**Comment by janhoy** [comment]
> 9.5 was just released, so I'd say it would be good to give a little bit of time before removing security updates for 9.4 at least. Otherwise I'm good with this.

I can agree to this. Let's keep 9.4.1 auto refreshed with Linux+JRE updates for yet some time to bring that added value during the window where users still is planning upgrades to 9.5.

**Comment by janhoy** [comment]
> Some automation or an explicit step would be good or this will get skipped in the future!

Perhaps rel.wizard could simply have a step asking RM to reflect over which versions to keep.

**Comment by ozlerhakan** [comment]
Hey, well, I'm sorry to bother you here as my question would be out of this topic. I'm wondering why `9.4.1`, `9.5`, `9.5.0`, `9.5.0-slim` don't support arm64, but `9` and `latest` do? Do you think there is an issue in those releases?

**Comment by HoustonPutman** [comment]
> Hey, well, I'm sorry to bother you here as my question would be out of this topic. I'm wondering why `9.4.1`, `9.5`, `9.5.0`, `9.5.0-slim` don't support arm64, but `9` and `latest` do? Do you think there is an issue in those releases?

I think that's an issue with either the official docker images team or with the Docker hub UI.... [As you can see here](https://github.com/docker-library/official-images/blob/master/library/solr#L11-L14), we put the architectures for all of the tags, not just latest or 9

**Pull request merged**
